"""Add hashed access_token, expiration, and used flag to User model

Revision ID: 06a2f743db97
Revises: c1638675d4c7
Create Date: 2025-11-18 01:19:28.999531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06a2f743db97'
down_revision = 'c1638675d4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('access_token_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_token_used', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('access_token'))
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('access_token'), ['access_token'], unique=True)
        batch_op.drop_column('access_token_used')
        batch_op.drop_column('access_token_expiration')
        batch_op.drop_column('access_token_hash')

    # ### end Alembic commands ###
