"""Add nama_lapangan and jenjang_keanggotaan to User model

Revision ID: 43f14990dd80
Revises: 4b18e3a23540
Create Date: 2025-11-14 03:15:38.195781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f14990dd80'
down_revision = '4b18e3a23540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_lapangan', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jenjang_keanggotaan', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('jenjang_keanggotaan')
        batch_op.drop_column('nama_lapangan')

    # ### end Alembic commands ###
