"""Add NIA field to User model

Revision ID: b8aeecc0d73d
Revises: 43f14990dd80
Create Date: 2025-11-14 03:22:46.887025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8aeecc0d73d'
down_revision = '43f14990dd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nia', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['nia'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nia')

    # ### end Alembic commands ###
