"""Add access_token and finalize user model for 2FA

Revision ID: c1638675d4c7
Revises: c61b3bb3e7af
Create Date: 2025-11-17 20:58:21.748411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1638675d4c7'
down_revision = 'c61b3bb3e7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['access_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
